module.exports = {
  nonSpendTransfers
};

function nonSpendTransfers() {
  return (nonSpendTransfers = [
    "INTERNET TRANSFER TO ONLINE SAVINGS ACCOUNT",
    "WELLS FARGO CARD CCPYMT",
    "DISCOVER E-PAYMENT",
    "CHASE CREDIT CRD EPAY",
    "AMERICAN EXPRESS",
    "APEX CLEARING ACH",
    "GAP VISA GAP EPAY~ FUTURE AMOUNT: 43.17 ~ TRAN: ACHDW",
    "CHASE CREDIT CRD EPAY~ FUTURE AMOUNT: 528.58 ~ TRAN: ACHDW",
    "STRIPE TRANSFER",
    "TRANSFER TO AMEX",
    "TRANSFER TO WELLS FARGO CREDIT CARD",
    "TRANSFER TO DISCOVER IT CARD",
    "CHASE CREDIT CRD EPAY~ FUTURE AMOUNT: 1143.97 ~ TRAN: ACHDW",
    "CHASE CREDIT CRD EPAY~ FUTURE AMOUNT: 311 ~ TRAN: ACHDW",
    "TRANSFER TO CHASE CREDIT CARD",
    "INTERNET TRANSFER ONLINE",
    "WELLS FARGO CCPYMT",
    "CHASE EPAY FUTURE",
    "DISCOVER E",
    "GAP GAP EPAY",
    "CHASE EPAY",
    "TRANSFER TO GENERAL SAVINGS",
    "ALLY BANK TRANSFER",
    "REQUESTED TRANSFER KYLE"
  ]);
}
