export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS";
export const FETCH_TRANSACTION = "FETCH_TRANSACTION";
export const AUTH_USER = "AUTH_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const GET_NAME = "GET_NAME";
export const SHOW_NETSPENDCHART = "SHOW_NETSPENDCHART";
export const SHOW_TOPCATEGORIESCHART = "SHOW_TOPCATEGORIESCHART";
export const SHOW_BANKINFOCHART = "SHOW_BANKINFOCHART";
